RPET-577 Adding and viewing notes is available to solicitors
hmcts/div-ccd-definitions pull request #573
Opened 2020-11-27 12:14 UTC by gurarach

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RPET-577

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-12-04 11:06 UTC, sameer4414 commented
Looks fine to me

2020-12-04 11:10 UTC, tzarsmango approved these changes
LGTM

2020-12-04 11:21 UTC, TSeelig approved these changes

2021-02-01 14:46 UTC, yarpo requested changes
It's going to be done as DIV-6713

2021-02-04 10:26 UTC, yarpo approved these changes

2021-02-16 14:34 UTC, closed without merging